import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { MOCK_DATA, POSTING_HEATMAP } from "@/data/mockData";

// ─── Brand palette ──────────────────────────────────────────────────────────
const C = {
  indigo:    [99,  102, 241] as [number, number, number],
  indigoDark:[55,  48,  163] as [number, number, number],
  dark:      [15,  23,  42]  as [number, number, number],
  slate700:  [51,  65,  85]  as [number, number, number],
  slate500:  [100, 116, 139] as [number, number, number],
  slate200:  [226, 232, 240] as [number, number, number],
  slate50:   [248, 250, 252] as [number, number, number],
  white:     [255, 255, 255] as [number, number, number],
  green:     [34,  197, 94]  as [number, number, number],
  amber:     [245, 158, 11]  as [number, number, number],
  red:       [239, 68,  68]  as [number, number, number],
};

const W = 210; // A4 width mm
const H = 297; // A4 height mm
const MARGIN = 18;

// ─── Helpers ─────────────────────────────────────────────────────────────────
function fill(doc: jsPDF, color: [number, number, number], x: number, y: number, w: number, h: number) {
  doc.setFillColor(...color);
  doc.rect(x, y, w, h, "F");
}

function text(doc: jsPDF, str: string, x: number, y: number, color: [number, number, number], size: number, style: "normal" | "bold" = "normal") {
  doc.setFont("helvetica", style);
  doc.setFontSize(size);
  doc.setTextColor(...color);
  doc.text(str, x, y);
}

function pageHeader(doc: jsPDF, pageNum: number) {
  fill(doc, C.indigo, 0, 0, W, 11);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.5);
  doc.setTextColor(...C.white);
  doc.text("RARE FITNESS", MARGIN, 7);
  doc.setFont("helvetica", "normal");
  doc.text("Social Media Analytics Report  ·  March 2026", MARGIN + 22, 7);
  doc.setFont("helvetica", "bold");
  doc.text(`PAGE ${pageNum}`, W - MARGIN, 7, { align: "right" });
}

function pageFooter(doc: jsPDF) {
  fill(doc, C.slate200, 0, H - 8, W, 8);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(6.5);
  doc.setTextColor(...C.slate500);
  doc.text("Confidential — Rare Fitness Internal Report", MARGIN, H - 3);
  doc.text("Generated by SMM Dashboard · Powered by Llama 3.3 70B", W - MARGIN, H - 3, { align: "right" });
}

function sectionTitle(doc: jsPDF, title: string, y: number) {
  fill(doc, C.slate50, MARGIN, y, W - MARGIN * 2, 7);
  doc.setDrawColor(...C.slate200);
  doc.setLineWidth(0.3);
  doc.rect(MARGIN, y, W - MARGIN * 2, 7, "S");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(...C.indigo);
  doc.text(title.toUpperCase(), MARGIN + 3, y + 4.8);
  return y + 11;
}

function kpiChip(doc: jsPDF, label: string, value: string, delta: string, positive: boolean, x: number, y: number, w: number) {
  fill(doc, C.slate50, x, y, w, 18);
  doc.setDrawColor(...C.slate200);
  doc.setLineWidth(0.3);
  doc.rect(x, y, w, 18, "S");

  fill(doc, positive ? C.green : C.red, x, y, 3, 18);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(6.5);
  doc.setTextColor(...C.slate500);
  doc.text(label, x + 6, y + 5.5);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...C.dark);
  doc.text(value, x + 6, y + 12.5);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  doc.setTextColor(...(positive ? C.green : C.red));
  doc.text(delta, x + 6, y + 17);
}

// ─── Cover Page ──────────────────────────────────────────────────────────────
function coverPage(doc: jsPDF) {
  fill(doc, C.dark, 0, 0, W, H);

  // Top indigo bar
  fill(doc, C.indigo, 0, 0, W, 5);

  // Side accent stripe
  fill(doc, C.indigo, 0, 0, 3, H);

  // Brand pill
  fill(doc, C.indigo, MARGIN, 28, 40, 8);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  doc.setTextColor(...C.white);
  doc.text("RARE FITNESS", MARGIN + 3.5, 33.5);

  // Big title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(30);
  doc.setTextColor(...C.white);
  doc.text("Social Media", MARGIN, 80);
  doc.text("Analytics", MARGIN, 95);
  doc.text("Report", MARGIN, 110);

  // Accent underline
  fill(doc, C.indigo, MARGIN, 116, 70, 1.5);

  // Period badge
  doc.setFontSize(13);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(148, 163, 184);
  doc.text("March 2026  ·  All Platforms", MARGIN, 128);

  // Divider line
  fill(doc, [30, 41, 59], MARGIN, 138, W - MARGIN * 2, 0.5);

  // Highlight stats row
  const stats = [
    { label: "Total Followers", value: "264,000" },
    { label: "Total Reach",     value: "2,64,000" },
    { label: "Avg Engagement",  value: "4.2%" },
    { label: "Content Published", value: "47 Posts" },
  ];
  const sw = (W - MARGIN * 2) / 4;
  stats.forEach((s, i) => {
    const sx = MARGIN + i * sw;
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...C.white);
    doc.text(s.value, sx, 152);
    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 116, 139);
    doc.text(s.label, sx, 158);
  });

  // Vertical stat separators
  for (let i = 1; i < 4; i++) {
    fill(doc, [30, 41, 59], MARGIN + i * sw - 2, 145, 0.5, 18);
  }

  // Bottom section
  fill(doc, [15, 23, 42], 0, H - 40, W, 40);
  fill(doc, C.indigo, 0, H - 40, W, 0.5);

  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...C.white);
  doc.text("Prepared by", MARGIN, H - 28);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(148, 163, 184);
  doc.setFontSize(7.5);
  doc.text("SMM Analytics Dashboard  ·  AI-Powered Insights by Llama 3.3 70B", MARGIN, H - 22);
  doc.text(`Report generated on ${new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}`, MARGIN, H - 16);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  doc.setTextColor(...C.indigo);
  doc.text("CONFIDENTIAL", W - MARGIN, H - 16, { align: "right" });
}

// ─── Page 2: Executive Summary ───────────────────────────────────────────────
function execSummaryPage(doc: jsPDF) {
  doc.addPage();
  pageHeader(doc, 2);
  pageFooter(doc);

  let y = 20;
  y = sectionTitle(doc, "Executive Summary — KPI Overview", y);

  // KPI chips (2 rows × 5 across)
  const kpis = [
    { label: "Total Followers",    value: "264,000",  delta: "+1.7% MoM", pos: true  },
    { label: "Follower Growth",    value: "+3,200",   delta: "+22% MoM",  pos: true  },
    { label: "Total Reach (Mar)",  value: "2,64,000", delta: "+18% MoM",  pos: true  },
    { label: "Avg Engagement Rate",value: "4.2%",     delta: "+0.4% MoM", pos: true  },
    { label: "Content Published",  value: "47 posts", delta: "22 IG · 14 YT · 11 FB", pos: true },
  ];
  const chipW = (W - MARGIN * 2 - 4 * 3) / 5;
  kpis.forEach((k, i) => {
    kpiChip(doc, k.label, k.value, k.delta, k.pos, MARGIN + i * (chipW + 3), y, chipW);
  });
  y += 24;

  // Platform summary sub-table
  y = sectionTitle(doc, "Platform at a Glance", y);

  autoTable(doc, {
    startY: y,
    margin: { left: MARGIN, right: MARGIN },
    head: [["Platform", "Followers", "MoM Growth", "Reach (Mar)", "Eng. Rate", "Key Stat"]],
    body: [
      ["Instagram", "1,85,000", "+340 (+0.2%)",  "1,42,000",  "4.8%", "68% Reels completion"],
      ["YouTube",   "8,200",    "+180 (+2.2%)",   "68,000 views", "2.8%", "44% avg retention · 2h 50m watch time"],
      ["Facebook",  "70,800",   "+120 (+0.2%)",   "54,000",    "1.6%", "Organic reach declining"],
    ],
    headStyles:          { fillColor: C.indigo, textColor: C.white, fontStyle: "bold", fontSize: 7.5 },
    bodyStyles:          { fontSize: 7.5, textColor: C.slate700 },
    alternateRowStyles:  { fillColor: C.slate50 },
    styles:              { cellPadding: 2.5 },
  });

  y = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 6;
  y = sectionTitle(doc, "Audience Geography Snapshot", y);

  autoTable(doc, {
    startY: y,
    margin: { left: MARGIN, right: MARGIN },
    head: [["#", "City / Region", "Province", "Audience", "Share of Total"]],
    body: MOCK_DATA.locations.slice(0, 7).map((l, i) => [
      i + 1,
      l.city,
      l.region,
      l.count.toLocaleString(),
      `${l.percentage}%`,
    ]),
    headStyles:         { fillColor: C.indigoDark, textColor: C.white, fontStyle: "bold", fontSize: 7.5 },
    bodyStyles:         { fontSize: 7.5, textColor: C.slate700 },
    alternateRowStyles: { fillColor: C.slate50 },
    styles:             { cellPadding: 2.5 },
    columnStyles:       { 0: { cellWidth: 10 }, 3: { halign: "right" }, 4: { halign: "right", fontStyle: "bold" } },
  });
}

// ─── Page 3: Content Performance ─────────────────────────────────────────────
function contentPage(doc: jsPDF) {
  doc.addPage();
  pageHeader(doc, 3);
  pageFooter(doc);

  let y = 20;
  y = sectionTitle(doc, "Content Performance — All Posts (March 2026)", y);

  const posts = MOCK_DATA.contentPosts;

  autoTable(doc, {
    startY: y,
    margin: { left: MARGIN, right: MARGIN },
    head: [["#", "Title", "Platform", "Type", "Date", "Reach", "Likes", "Comments", "ER%"]],
    body: posts.map((p, i) => [
      i + 1,
      p.title,
      p.platform.charAt(0).toUpperCase() + p.platform.slice(1),
      p.type,
      p.date,
      p.reach.toLocaleString(),
      p.likes.toLocaleString(),
      p.comments.toLocaleString(),
      `${p.engagementRate}%`,
    ]),
    headStyles:         { fillColor: C.indigo, textColor: C.white, fontStyle: "bold", fontSize: 7 },
    bodyStyles:         { fontSize: 7, textColor: C.slate700 },
    alternateRowStyles: { fillColor: C.slate50 },
    styles:             { cellPadding: 2.2 },
    columnStyles: {
      0: { cellWidth: 8,  halign: "center" },
      1: { cellWidth: 48 },
      2: { cellWidth: 20 },
      3: { cellWidth: 18 },
      4: { cellWidth: 24 },
      5: { halign: "right" },
      6: { halign: "right" },
      7: { halign: "right" },
      8: { halign: "right", fontStyle: "bold" },
    },
  });

  y = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 6;
  y = sectionTitle(doc, "Video Completion Rates", y);

  autoTable(doc, {
    startY: y,
    margin: { left: MARGIN, right: MARGIN },
    head: [["Platform", "Avg Completion Rate", "Avg Views", "Source / Note"]],
    body: MOCK_DATA.videoCompletion.map((v) => [
      v.label,
      `${v.completionRate}%`,
      v.avgViews,
      v.platform === "instagram" ? "Meta Graph API · video_insights"
        : v.platform === "youtube" ? "YouTube Analytics · audienceRetention"
        : "Estimated (limited Meta API data)",
    ]),
    headStyles:         { fillColor: C.indigoDark, textColor: C.white, fontStyle: "bold", fontSize: 7.5 },
    bodyStyles:         { fontSize: 7.5, textColor: C.slate700 },
    alternateRowStyles: { fillColor: C.slate50 },
    styles:             { cellPadding: 2.5 },
    columnStyles:       { 1: { halign: "center", fontStyle: "bold" }, 2: { halign: "center" } },
  });
}

// ─── Page 4: Funnel + Heatmap ─────────────────────────────────────────────────
function funnelPage(doc: jsPDF) {
  doc.addPage();
  pageHeader(doc, 4);
  pageFooter(doc);

  let y = 20;
  y = sectionTitle(doc, "Post-to-Lead Attribution Funnel — March 2026", y);

  autoTable(doc, {
    startY: y,
    margin: { left: MARGIN, right: MARGIN },
    head: [["Stage", "Count", "Rate / Detail", "Conversion from Previous"]],
    body: MOCK_DATA.attributionFunnel.map((s) => [
      s.stage,
      typeof s.count === "number" ? s.count.toLocaleString() : String(s.count),
      s.rate ?? "—",
      s.conversionFromPrev !== undefined ? `${s.conversionFromPrev}%` : "—",
    ]),
    headStyles:         { fillColor: C.indigo, textColor: C.white, fontStyle: "bold", fontSize: 7.5 },
    bodyStyles:         { fontSize: 7.5, textColor: C.slate700 },
    alternateRowStyles: { fillColor: C.slate50 },
    styles:             { cellPadding: 2.5 },
    columnStyles:       { 1: { halign: "right", fontStyle: "bold" }, 3: { halign: "center", fontStyle: "bold" } },
  });

  y = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 6;
  y = sectionTitle(doc, "Best Time to Post — Engagement Index (0–100)", y);

  // Heatmap as table
  const { days, hours, scores } = POSTING_HEATMAP;
  autoTable(doc, {
    startY: y,
    margin: { left: MARGIN, right: MARGIN },
    head: [["Day", ...hours]],
    body: days.map((d, di) => [d, ...scores[di].map(String)]),
    headStyles:         { fillColor: C.indigoDark, textColor: C.white, fontStyle: "bold", fontSize: 7 },
    bodyStyles:         { fontSize: 7, textColor: C.slate700, halign: "center" },
    alternateRowStyles: { fillColor: C.slate50 },
    styles:             { cellPadding: 2 },
    columnStyles:       { 0: { fontStyle: "bold", halign: "left" } },
    didParseCell: (data) => {
      if (data.section === "body" && data.column.index > 0) {
        const v = parseInt(data.cell.raw as string, 10);
        if (v >= 88)      data.cell.styles.fillColor = [99,  102, 241];
        else if (v >= 80) data.cell.styles.fillColor = [129, 140, 248];
        else if (v >= 70) data.cell.styles.fillColor = [165, 180, 252];
        else if (v >= 55) data.cell.styles.fillColor = [199, 210, 254];
        else if (v >= 40) data.cell.styles.fillColor = [224, 231, 255];

        if (v >= 80) data.cell.styles.textColor = [255, 255, 255];
        if (v >= 88) data.cell.styles.fontStyle = "bold";
      }
    },
  });

  y = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 5;
  fill(doc, [240, 253, 244], MARGIN, y, W - MARGIN * 2, 14);
  doc.setDrawColor(134, 239, 172);
  doc.setLineWidth(0.3);
  doc.rect(MARGIN, y, W - MARGIN * 2, 14, "S");
  fill(doc, C.green, MARGIN, y, 3, 14);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.5);
  doc.setTextColor(21, 128, 61);
  doc.text("KEY INSIGHT", MARGIN + 6, y + 5.5);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(22, 101, 52);
  doc.text(POSTING_HEATMAP.insight, MARGIN + 6, y + 11, { maxWidth: W - MARGIN * 2 - 10 });
}

// ─── Main export function ─────────────────────────────────────────────────────
export function exportPDF() {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  coverPage(doc);
  execSummaryPage(doc);
  contentPage(doc);
  funnelPage(doc);

  doc.save(`rarefitness-smm-report-march2026.pdf`);
}
